language: node_js

node_js:
  - "stable"

env:
  - TEST_CONFIG=eslint
  - TEST_CONFIG=basic

matrix:
  allow_failures:
    - env: TEST_CONFIG=basic

script:
  - export GITHUB_BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)
  - echo "GITHUB_BRANCH=$GITHUB_BRANCH, TRAVIS_BRANCH=$TRAVIS_BRANCH, TRAVIS_PULL_REQUEST_BRANCH=$TRAVIS_PULL_REQUEST_BRANCH"
  - npm test

notifications:
  email: false
  slack: orange-cloud:NU4pReu2sxFcJkUl8v6qTAPu
